apiVersion: v1
entries:
  identity:
  - apiVersion: v2
    appVersion: 0.5.3
    created: "2021-04-13T13:18:02.017984348Z"
    description: wemogy Identity Provider
    digest: 7eb482f3d5648ee14a35621bcf825f2a39f72c092a7d71a66ebf2a40201f19a6
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.5.3.tgz
    version: 0.5.3
  - apiVersion: v2
    appVersion: 0.5.2
    created: "2021-04-13T13:18:02.017341598Z"
    description: wemogy Identity Provider
    digest: 4be032d303fb9f507d85f40c7bc8899aefce261a79511e79281ce42506744faa
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.5.2.tgz
    version: 0.5.2
  - apiVersion: v2
    appVersion: 0.5.1
    created: "2021-04-13T13:18:02.016747452Z"
    description: wemogy Identity Provider
    digest: bb736d554b8914df0da7a50f4f72b39294a3593a8edfc24363fff44ffe740570
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.5.1.tgz
    version: 0.5.1
  - apiVersion: v2
    appVersion: 0.5.0
    created: "2021-04-13T13:18:02.016160406Z"
    description: wemogy Identity Provider
    digest: 1ce4bfc0065200a2a26be6163a03367088e2486139ff3609e025c7f0e324e5f3
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: 0.4.4
    created: "2021-04-13T13:18:02.015473353Z"
    description: wemogy Identity Provider
    digest: cde48836c3cab2f91abc135c005072d3c53af0b2b6921c7c1d810d58b11bfce8
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.4.4.tgz
    version: 0.4.4
  identity-demo:
  - apiVersion: v2
    appVersion: 0.5.3
    created: "2021-04-13T13:18:02.020443439Z"
    description: wemogy Identity Provider Demo Apps
    digest: 40c86460b8322026ebda8150d29e9ce7f76e5c718729aaedb15a845b6ea5f9a6
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.5.3.tgz
    version: 0.5.3
  - apiVersion: v2
    appVersion: 0.5.2
    created: "2021-04-13T13:18:02.020083911Z"
    description: wemogy Identity Provider Demo Apps
    digest: 893323479de00aac8cbb58927566d2a39b847445f6a2a3fa30657edeb51b4a59
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.5.2.tgz
    version: 0.5.2
  - apiVersion: v2
    appVersion: 0.5.1
    created: "2021-04-13T13:18:02.019708282Z"
    description: wemogy Identity Provider Demo Apps
    digest: 4350c101c1ce91bb8075bc80a506971abe65b2471a9d9df274032454a77701cf
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.5.1.tgz
    version: 0.5.1
  - apiVersion: v2
    appVersion: 0.5.0
    created: "2021-04-13T13:18:02.018758208Z"
    description: wemogy Identity Provider Demo Apps
    digest: a10e50c381355081c33e7a526d12322792ef466c1bb78ffe7998b3722e475f34
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: 0.4.4
    created: "2021-04-13T13:18:02.018379879Z"
    description: wemogy Identity Provider Demo Apps
    digest: 11564647b0c62892b419b557e8c3313ac71bba59c5dffbc2062b9f02f07a5221
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.4.4.tgz
    version: 0.4.4
generated: "2021-04-13T13:18:02.014671691Z"
