apiVersion: v1
entries:
  identity:
  - apiVersion: v2
    appVersion: 0.5.5
    created: "2021-04-14T16:12:27.70199629Z"
    description: wemogy Identity Provider
    digest: 618a940b1ad5a4883494b80a8354d466301bb815fd78dd74df618bda8b1aeca8
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.5.5.tgz
    version: 0.5.5
  - apiVersion: v2
    appVersion: 0.5.4
    created: "2021-04-14T16:12:27.700975576Z"
    description: wemogy Identity Provider
    digest: 3b451672cafd8298e358b1562480f41929cfcf583cefdc4207a13a70a1c17945
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.5.4.tgz
    version: 0.5.4
  - apiVersion: v2
    appVersion: 0.5.3
    created: "2021-04-14T16:12:27.698960847Z"
    description: wemogy Identity Provider
    digest: 7eb482f3d5648ee14a35621bcf825f2a39f72c092a7d71a66ebf2a40201f19a6
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.5.3.tgz
    version: 0.5.3
  - apiVersion: v2
    appVersion: 0.5.2
    created: "2021-04-14T16:12:27.697914533Z"
    description: wemogy Identity Provider
    digest: 4be032d303fb9f507d85f40c7bc8899aefce261a79511e79281ce42506744faa
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.5.2.tgz
    version: 0.5.2
  - apiVersion: v2
    appVersion: 0.5.1
    created: "2021-04-14T16:12:27.69701042Z"
    description: wemogy Identity Provider
    digest: bb736d554b8914df0da7a50f4f72b39294a3593a8edfc24363fff44ffe740570
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.5.1.tgz
    version: 0.5.1
  - apiVersion: v2
    appVersion: 0.5.0
    created: "2021-04-14T16:12:27.696149308Z"
    description: wemogy Identity Provider
    digest: 1ce4bfc0065200a2a26be6163a03367088e2486139ff3609e025c7f0e324e5f3
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: 0.4.4
    created: "2021-04-14T16:12:27.695284796Z"
    description: wemogy Identity Provider
    digest: cde48836c3cab2f91abc135c005072d3c53af0b2b6921c7c1d810d58b11bfce8
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.4.4.tgz
    version: 0.4.4
  identity-demo:
  - apiVersion: v2
    appVersion: 0.5.5
    created: "2021-04-14T16:12:27.705228335Z"
    description: wemogy Identity Provider Demo Apps
    digest: f61948f8b60da41d69ac6714192c0a4c3a52759340e34ccda2f03e0a735a7b9b
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.5.5.tgz
    version: 0.5.5
  - apiVersion: v2
    appVersion: 0.5.4
    created: "2021-04-14T16:12:27.704706828Z"
    description: wemogy Identity Provider Demo Apps
    digest: 8863679b3a1c8a4e8407593b3ca4bf02f7cf85c93403b62c70671f2dec1a19ad
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.5.4.tgz
    version: 0.5.4
  - apiVersion: v2
    appVersion: 0.5.3
    created: "2021-04-14T16:12:27.704270222Z"
    description: wemogy Identity Provider Demo Apps
    digest: 40c86460b8322026ebda8150d29e9ce7f76e5c718729aaedb15a845b6ea5f9a6
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.5.3.tgz
    version: 0.5.3
  - apiVersion: v2
    appVersion: 0.5.2
    created: "2021-04-14T16:12:27.703860416Z"
    description: wemogy Identity Provider Demo Apps
    digest: 893323479de00aac8cbb58927566d2a39b847445f6a2a3fa30657edeb51b4a59
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.5.2.tgz
    version: 0.5.2
  - apiVersion: v2
    appVersion: 0.5.1
    created: "2021-04-14T16:12:27.70343651Z"
    description: wemogy Identity Provider Demo Apps
    digest: 4350c101c1ce91bb8075bc80a506971abe65b2471a9d9df274032454a77701cf
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.5.1.tgz
    version: 0.5.1
  - apiVersion: v2
    appVersion: 0.5.0
    created: "2021-04-14T16:12:27.702992604Z"
    description: wemogy Identity Provider Demo Apps
    digest: a10e50c381355081c33e7a526d12322792ef466c1bb78ffe7998b3722e475f34
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: 0.4.4
    created: "2021-04-14T16:12:27.702553198Z"
    description: wemogy Identity Provider Demo Apps
    digest: 11564647b0c62892b419b557e8c3313ac71bba59c5dffbc2062b9f02f07a5221
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.4.4.tgz
    version: 0.4.4
generated: "2021-04-14T16:12:27.69410738Z"
