apiVersion: v1
entries:
  identity:
  - apiVersion: v2
    appVersion: 0.8.10
    created: "2021-07-10T20:08:14.026476835Z"
    description: wemogy Identity Provider
    digest: af6ec0fead00e1afe83403742bfd7b121067c0bb0e0d87a6e8d31524b45a3d69
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.8.10.tgz
    version: 0.8.10
  - apiVersion: v2
    appVersion: 0.8.9
    created: "2021-07-10T20:08:14.033890335Z"
    description: wemogy Identity Provider
    digest: 875f53aff15afdfcf9768c09228392f82083b98b2c43e8a5410b9549379acef7
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.8.9.tgz
    version: 0.8.9
  - apiVersion: v2
    appVersion: 0.8.8
    created: "2021-07-10T20:08:14.032657219Z"
    description: wemogy Identity Provider
    digest: 5492509e6264efb733bf1391d39f67ff7bb0706968b23d8c61d705ac2d1b1c74
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.8.8.tgz
    version: 0.8.8
  - apiVersion: v2
    appVersion: 0.8.7
    created: "2021-07-10T20:08:14.031795007Z"
    description: wemogy Identity Provider
    digest: a4c062b0574063414214e5d68b0060ddebe9f196e1013d35cc677f779d109583
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.8.7.tgz
    version: 0.8.7
  - apiVersion: v2
    appVersion: 0.8.6
    created: "2021-07-10T20:08:14.030985496Z"
    description: wemogy Identity Provider
    digest: d25ba3da92dc1fe64c9ad6152cbc9b1f21520c58caf472a2192cb815c1d9ccda
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.8.6.tgz
    version: 0.8.6
  - apiVersion: v2
    appVersion: 0.8.5
    created: "2021-07-10T20:08:14.030227486Z"
    description: wemogy Identity Provider
    digest: 458d132d8fdff43f54d92fe75a9ea16f44c8f22341af990db8d8e9936c489183
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.8.5.tgz
    version: 0.8.5
  - apiVersion: v2
    appVersion: 0.8.4
    created: "2021-07-10T20:08:14.029514876Z"
    description: wemogy Identity Provider
    digest: ba5f65196f02b900b6997167759e7c5cf42c83dff9ad0c4be2ce5f6e2dec4e15
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.8.4.tgz
    version: 0.8.4
  - apiVersion: v2
    appVersion: 0.8.3
    created: "2021-07-10T20:08:14.028731966Z"
    description: wemogy Identity Provider
    digest: d5b0588bf6dd94da77ac3801b10ffc809644c3ec6a257c6fbfb9e70c316531b2
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.8.3.tgz
    version: 0.8.3
  - apiVersion: v2
    appVersion: 0.8.2
    created: "2021-07-10T20:08:14.027195645Z"
    description: wemogy Identity Provider
    digest: ebe646621cfda445f897adcc2613cef66c4fb15116fe21a7e8bb8bd6dcbd4ec1
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.8.2.tgz
    version: 0.8.2
  - apiVersion: v2
    appVersion: 0.8.1
    created: "2021-07-10T20:08:14.025513222Z"
    description: wemogy Identity Provider
    digest: f30859df7bae0c340c8cd62807c45be5af6d8d0910cad4fc3d7aa186e70565a4
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.8.1.tgz
    version: 0.8.1
  - apiVersion: v2
    appVersion: 0.8.0
    created: "2021-07-10T20:08:14.02464191Z"
    description: wemogy Identity Provider
    digest: 87bd2c19b8945c5edb22893ac2cb8807a7dc999cf6a5f1d08b911341445853ba
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.8.0.tgz
    version: 0.8.0
  - apiVersion: v2
    appVersion: 0.7.0
    created: "2021-07-10T20:08:14.0238759Z"
    description: wemogy Identity Provider
    digest: 4eb32c65c389123016130b9bc53fc3e6f521664d70977ab32e46fbb0db74ae8c
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v2
    appVersion: 0.6.3
    created: "2021-07-10T20:08:14.02163047Z"
    description: wemogy Identity Provider
    digest: 96d3bc592b51209331a4b5a1f58c77686def56b56d163ee489fa1f5ebe32eb87
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.6.3.tgz
    version: 0.6.3
  - apiVersion: v2
    appVersion: 0.6.2
    created: "2021-07-10T20:08:14.018336525Z"
    description: wemogy Identity Provider
    digest: 0f218836c0a8ed266caf536783dbecf473e844937461953e6ff2192225559cab
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.6.2.tgz
    version: 0.6.2
  - apiVersion: v2
    appVersion: 0.6.1
    created: "2021-07-10T20:08:14.017125609Z"
    description: wemogy Identity Provider
    digest: 84999760c0f5e09c44f72c44bb71e9caa1d94b3d35675303429d6b9e7f825c0a
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.6.1.tgz
    version: 0.6.1
  - apiVersion: v2
    appVersion: 0.5.5
    created: "2021-07-10T20:08:14.013168855Z"
    description: wemogy Identity Provider
    digest: 618a940b1ad5a4883494b80a8354d466301bb815fd78dd74df618bda8b1aeca8
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.5.5.tgz
    version: 0.5.5
  - apiVersion: v2
    appVersion: 0.5.4
    created: "2021-07-10T20:08:14.00977661Z"
    description: wemogy Identity Provider
    digest: 3b451672cafd8298e358b1562480f41929cfcf583cefdc4207a13a70a1c17945
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.5.4.tgz
    version: 0.5.4
  - apiVersion: v2
    appVersion: 0.5.3
    created: "2021-07-10T20:08:14.008973999Z"
    description: wemogy Identity Provider
    digest: 7eb482f3d5648ee14a35621bcf825f2a39f72c092a7d71a66ebf2a40201f19a6
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.5.3.tgz
    version: 0.5.3
  - apiVersion: v2
    appVersion: 0.5.2
    created: "2021-07-10T20:08:14.008389091Z"
    description: wemogy Identity Provider
    digest: 4be032d303fb9f507d85f40c7bc8899aefce261a79511e79281ce42506744faa
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.5.2.tgz
    version: 0.5.2
  - apiVersion: v2
    appVersion: 0.5.1
    created: "2021-07-10T20:08:14.007770782Z"
    description: wemogy Identity Provider
    digest: bb736d554b8914df0da7a50f4f72b39294a3593a8edfc24363fff44ffe740570
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.5.1.tgz
    version: 0.5.1
  - apiVersion: v2
    appVersion: 0.5.0
    created: "2021-07-10T20:08:14.006930671Z"
    description: wemogy Identity Provider
    digest: 1ce4bfc0065200a2a26be6163a03367088e2486139ff3609e025c7f0e324e5f3
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: 0.4.4
    created: "2021-07-10T20:08:14.006324563Z"
    description: wemogy Identity Provider
    digest: cde48836c3cab2f91abc135c005072d3c53af0b2b6921c7c1d810d58b11bfce8
    name: identity
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-0.4.4.tgz
    version: 0.4.4
  identity-demo:
  - apiVersion: v2
    appVersion: 0.8.10
    created: "2021-07-10T20:08:14.041714941Z"
    description: wemogy Identity Provider Demo Apps
    digest: 2871a4e92527e8dd20f425f911e7b7b2ae0d05012bfe32e53761b2919a15092f
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.8.10.tgz
    version: 0.8.10
  - apiVersion: v2
    appVersion: 0.8.9
    created: "2021-07-10T20:08:14.044692281Z"
    description: wemogy Identity Provider Demo Apps
    digest: 0ade104a061decedde0ef1f834bf4d923b9e56501936cc85df81081e0a9b46bf
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.8.9.tgz
    version: 0.8.9
  - apiVersion: v2
    appVersion: 0.8.8
    created: "2021-07-10T20:08:14.044323876Z"
    description: wemogy Identity Provider Demo Apps
    digest: 057756d2d76074f0508e42479cb05be71050bb741e2eefdc5983ff7754d2a7fd
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.8.8.tgz
    version: 0.8.8
  - apiVersion: v2
    appVersion: 0.8.7
    created: "2021-07-10T20:08:14.043954071Z"
    description: wemogy Identity Provider Demo Apps
    digest: 6146e9dc4f5cb476faf40e82dbbfe9653637be1616f2b1e7b345a23ef7e21ab4
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.8.7.tgz
    version: 0.8.7
  - apiVersion: v2
    appVersion: 0.8.6
    created: "2021-07-10T20:08:14.043576766Z"
    description: wemogy Identity Provider Demo Apps
    digest: 980fe4e146f018d0c67209f4fc938db407dfba1bd6f4da68221e51375250509a
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.8.6.tgz
    version: 0.8.6
  - apiVersion: v2
    appVersion: 0.8.5
    created: "2021-07-10T20:08:14.043206161Z"
    description: wemogy Identity Provider Demo Apps
    digest: 2b07d0a207190b648b7456ca6840a897ba7ddf164456f1affcf8405b9e20cad4
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.8.5.tgz
    version: 0.8.5
  - apiVersion: v2
    appVersion: 0.8.4
    created: "2021-07-10T20:08:14.042802456Z"
    description: wemogy Identity Provider Demo Apps
    digest: 9ed9429b72f946949dc4f157296c8d6bcbb4c0830fc19a5b114e4a1efbe8775c
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.8.4.tgz
    version: 0.8.4
  - apiVersion: v2
    appVersion: 0.8.3
    created: "2021-07-10T20:08:14.042460151Z"
    description: wemogy Identity Provider Demo Apps
    digest: 30357a3da3ff678b86e14b870fa99b248492e7a36e7ff52b0e18765b57621302
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.8.3.tgz
    version: 0.8.3
  - apiVersion: v2
    appVersion: 0.8.2
    created: "2021-07-10T20:08:14.042086146Z"
    description: wemogy Identity Provider Demo Apps
    digest: 62e8053bb12e6e78acf1bda1bcf01cc013faa236b11f7185460a2549f950d730
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.8.2.tgz
    version: 0.8.2
  - apiVersion: v2
    appVersion: 0.8.1
    created: "2021-07-10T20:08:14.041341936Z"
    description: wemogy Identity Provider Demo Apps
    digest: 1b260438a3f45339c2853f3aa2f441978a495d80fee4d1db58ea283e84821691
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.8.1.tgz
    version: 0.8.1
  - apiVersion: v2
    appVersion: 0.8.0
    created: "2021-07-10T20:08:14.040949631Z"
    description: wemogy Identity Provider Demo Apps
    digest: da8e7850a110c37df1dc0e86d5812d474967e4fb1d60bfde71db4370bb9141f5
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.8.0.tgz
    version: 0.8.0
  - apiVersion: v2
    appVersion: 0.7.0
    created: "2021-07-10T20:08:14.040575426Z"
    description: wemogy Identity Provider Demo Apps
    digest: fa648d11c3a0c5c22966c0f6a4afd781d6404702b8a98b2aa0eee41e16b296b9
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v2
    appVersion: 0.6.3
    created: "2021-07-10T20:08:14.04018562Z"
    description: wemogy Identity Provider Demo Apps
    digest: 135a7b6675431ac6a7008dec70cac80f61ce505aa6010cfb09622aa607b80ff6
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.6.3.tgz
    version: 0.6.3
  - apiVersion: v2
    appVersion: 0.6.2
    created: "2021-07-10T20:08:14.039783115Z"
    description: wemogy Identity Provider Demo Apps
    digest: 9be27ae8fe0327d518970ec7a14d7f449d134723b9222b4bbf70b4de16bc9efb
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.6.2.tgz
    version: 0.6.2
  - apiVersion: v2
    appVersion: 0.6.1
    created: "2021-07-10T20:08:14.039379309Z"
    description: wemogy Identity Provider Demo Apps
    digest: 8f3b77f633ef5141e1888dd01e35f7bfbb017da716e0f78434ea02c80c53ef88
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.6.1.tgz
    version: 0.6.1
  - apiVersion: v2
    appVersion: 0.5.5
    created: "2021-07-10T20:08:14.038961104Z"
    description: wemogy Identity Provider Demo Apps
    digest: f61948f8b60da41d69ac6714192c0a4c3a52759340e34ccda2f03e0a735a7b9b
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.5.5.tgz
    version: 0.5.5
  - apiVersion: v2
    appVersion: 0.5.4
    created: "2021-07-10T20:08:14.038370096Z"
    description: wemogy Identity Provider Demo Apps
    digest: 8863679b3a1c8a4e8407593b3ca4bf02f7cf85c93403b62c70671f2dec1a19ad
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.5.4.tgz
    version: 0.5.4
  - apiVersion: v2
    appVersion: 0.5.3
    created: "2021-07-10T20:08:14.037428283Z"
    description: wemogy Identity Provider Demo Apps
    digest: 40c86460b8322026ebda8150d29e9ce7f76e5c718729aaedb15a845b6ea5f9a6
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.5.3.tgz
    version: 0.5.3
  - apiVersion: v2
    appVersion: 0.5.2
    created: "2021-07-10T20:08:14.036778274Z"
    description: wemogy Identity Provider Demo Apps
    digest: 893323479de00aac8cbb58927566d2a39b847445f6a2a3fa30657edeb51b4a59
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.5.2.tgz
    version: 0.5.2
  - apiVersion: v2
    appVersion: 0.5.1
    created: "2021-07-10T20:08:14.036063065Z"
    description: wemogy Identity Provider Demo Apps
    digest: 4350c101c1ce91bb8075bc80a506971abe65b2471a9d9df274032454a77701cf
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.5.1.tgz
    version: 0.5.1
  - apiVersion: v2
    appVersion: 0.5.0
    created: "2021-07-10T20:08:14.034841648Z"
    description: wemogy Identity Provider Demo Apps
    digest: a10e50c381355081c33e7a526d12322792ef466c1bb78ffe7998b3722e475f34
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: 0.4.4
    created: "2021-07-10T20:08:14.034385142Z"
    description: wemogy Identity Provider Demo Apps
    digest: 11564647b0c62892b419b557e8c3313ac71bba59c5dffbc2062b9f02f07a5221
    name: identity-demo
    type: application
    urls:
    - https://wemogy.github.io/helm/charts/identity-demo-0.4.4.tgz
    version: 0.4.4
generated: "2021-07-10T20:08:14.005500552Z"
