name: Generate Helm Index
on:
  workflow_dispatch:
  push:
    paths:
    - 'charts/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - run: helm repo index --url https://wemogy.github.io/helm/charts charts
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.1.1
        with:                    
          branch: main
          message: 'Updates Helm Index'
          push: true
      
